# Base Parameters
factory = "0x0000000000FFe8B47B3e2130213B802212439497"
caller = "0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045"
codehash = "0x64e604787cbf194841e7b68d7cd28786f6c9a0a3ab9f8b0a0e87cb4387ab0107"

# Extra Parameters
worksize = 0x4400000
pattern = "010101"
